### ISSUE TITLE
Change for Germany's VAT on 1st July

### ISSUE THREAD

**Issue by Betree** [staaky/vatrates#10]
As per https://www.avalara.com/vatlive/en/vat-news/germany-cuts-vat-from-19--to-16--until-dec-2020.html:

> Germany has announced a €130billion COVID-19 stimulus package including a cut in the standard Value Added Tax rate from 19% to 16% from 1 July to 31 December 2020.  The reduced VAT rate of 7% will also be cut to 5%.

**Comment by Reicr** [comment]
Would be great to know if there will be an update to include this temporary change, since we would have to take other measures otherwise.

**Comment by mupat** [comment]
See #11 
Hope that module is still kinda maintained.

**Comment by staaky** [comment]
Thanks for the merge request, I've merged it into 2.0.3.
