### ISSUE TITLE
Add method to retrieve all VAT rates

### ISSUE THREAD

**Issue by sergio-domingues** [staaky/vatrates#7]
It would be helpful to have a method that returns all countries' VAT rates (bulk):

```json
"countries" : [
  {
    "country" : "Portugal",
    "stdRate": "23",
     ...
  },
  ...
]

```

**Comment by njoerd114** [comment]
It's already there:
for PHP: https://github.com/staaky/vatrates/blob/master/src/php/VATRates.php#L215
for JS: https://github.com/staaky/vatrates/blob/master/src/js/vatrates.js#L155

**Comment by sergio-domingues** [comment]
You're right I found it a while after publishing the issue and forgot to close it, sorry.
